# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './ui/rsa.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(876, 425)
        self.plain_text = QtWidgets.QTextEdit(Dialog)
        self.plain_text.setGeometry(QtCore.QRect(150, 90, 271, 91))
        self.plain_text.setObjectName("plain_text")
        self.cipher_text = QtWidgets.QTextEdit(Dialog)
        self.cipher_text.setGeometry(QtCore.QRect(150, 190, 271, 131))
        self.cipher_text.setObjectName("cipher_text")
        self.sign = QtWidgets.QTextEdit(Dialog)
        self.sign.setGeometry(QtCore.QRect(550, 90, 281, 91))
        self.sign.setObjectName("sign")
        self.verify_text = QtWidgets.QTextEdit(Dialog)
        self.verify_text.setGeometry(QtCore.QRect(550, 190, 281, 131))
        self.verify_text.setObjectName("verify_text")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(30, 100, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(30, 210, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(430, 100, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(440, 210, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.btn_gen_keys = QtWidgets.QToolButton(Dialog)
        self.btn_gen_keys.setGeometry(QtCore.QRect(550, 50, 151, 31))
        self.btn_gen_keys.setObjectName("btn_gen_keys")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(330, 10, 161, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.btn_encrypt = QtWidgets.QToolButton(Dialog)
        self.btn_encrypt.setGeometry(QtCore.QRect(110, 340, 151, 31))
        self.btn_encrypt.setObjectName("btn_encrypt")
        self.btn_decrypt = QtWidgets.QToolButton(Dialog)
        self.btn_decrypt.setGeometry(QtCore.QRect(270, 340, 151, 31))
        self.btn_decrypt.setObjectName("btn_decrypt")
        self.btn_sign = QtWidgets.QToolButton(Dialog)
        self.btn_sign.setGeometry(QtCore.QRect(520, 340, 151, 31))
        self.btn_sign.setObjectName("btn_sign")
        self.btn_verify = QtWidgets.QToolButton(Dialog)
        self.btn_verify.setGeometry(QtCore.QRect(680, 340, 151, 31))
        self.btn_verify.setObjectName("btn_verify")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Plain_text"))
        self.label_2.setText(_translate("Dialog", "Cipher_text"))
        self.label_3.setText(_translate("Dialog", "Information"))
        self.label_4.setText(_translate("Dialog", "Signature"))
        self.btn_gen_keys.setText(_translate("Dialog", "Generate keys"))
        self.label_5.setText(_translate("Dialog", "RSA Cipher"))
        self.btn_encrypt.setText(_translate("Dialog", "Encrypt"))
        self.btn_decrypt.setText(_translate("Dialog", "Decrypt"))
        self.btn_sign.setText(_translate("Dialog", "Sign"))
        self.btn_verify.setText(_translate("Dialog", "Verify"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
